

# Add 'test' label to any change to *.spec.js files within the source dir
'class':
- any: ['class.*.php']



# Add 'frontend` label to any change to *.js files as long as the `main.js` hasn't changed
frontend:
- any: ['*.tpl','*.js','*.css']
